import matplotlib.pyplot as plt

# Advertising channels
channels = ["TV", "Digital Ads", "Social Media", "Email Marketing", "Influencer Campaigns"]

# Corresponding online sales generated by each channel
sales = [11300, 12780, 9920, 8450, 10970]

# Create a new figure
plt.figure(figsize=(10,6))

# Plot the data using a stair plot
plt.step(channels, sales, where='mid')

# Add a title
plt.title("Effectiveness of Different Advertising Channels in Generating Online Sales")

# Label the X and Y axes
plt.xlabel("Advertising Channels")
plt.ylabel("Online Sales (in USD)")

# Change the edge color of the points that contain the center point of the bounding box to #c56e60
plt.scatter(channels, sales, c='black', edgecolor='#c56e60', zorder=16, offset=(2.58, 2.97))

# Display the plot
plt.tight_layout()
plt.savefig("figure.png")