import matplotlib.pyplot as plt
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.patches as patches
import matplotlib.transforms as mtransforms
import matplotlib.collections as mcoll
import matplotlib.path as mpath
import matplotlib.transforms as mtransforms
import matplotlib.p