from matplotlib.patches import PathPatch
from matplotlib.transforms import Bbox
from matplotlib.patches import PathPatch
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox
from matplotlib.transforms import Bbox