import matplotlib.pyplot as plt
import numpy as np

# different periods categories ('Pre-covid', 'Lockdown', 'Recovery', 'Post-covid')
stages = np.array([0, 1, 2, 3])

# randomly generated revenue for each destination.
Paris = np.array([200, 80, 150, 210])
New_York = np.array([220, 60, 160, 205])
Rome = np.array([210, 70, 140, 220])
Tokyo = np.array([230, 75, 150, 215])
London = np.array([220, 65, 155, 210])

# Plotting using matplotlib's step function
plt.figure(figsize=(10,6))
plt.step(stages, Paris, where='mid', label='Paris', linestyle='dashed', markeredgecolor='black', markeredgewidth=1.98, marker='*')
plt.step(stages, New_York, where='mid', label='New York', linestyle='dashed', markeredgecolor='black', markeredgewidth=1.98, marker='*')
plt.step(stages, Rome, where='mid', label='Rome', linestyle='dashed', markeredgecolor='black', markeredgewidth=1.98, marker='*')
plt.step(stages, Tokyo, where='mid', label='Tokyo', linestyle='dashed', markeredgecolor='black', markeredgewidth=1.98, marker='*')
plt.step(stages, London, where='mid', label='London', linestyle='dashed', markeredgecolor='black', markeredgewidth=1.98, marker='*')

plt.xticks(stages, ['Pre-COVID', 'Lockdown', 'Recovery', 'Post-COVID'])
plt.yticks(np.arange(0,250,50))

plt.legend()
plt.title('Revenue Generated by Popular Destinations during COVID-19')
plt.xlabel('COVID-19 Stages')
plt.ylabel('Revenue (in Billions)')
plt.grid(True)
plt.tight_layout()
plt.savefig("figure.png")