from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.patches import PathPatch
from matplotlib.transforms import Affine2D, Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms import Affine2D as A2D
from matplotlib.transforms