from matplotlib.figure import Figure
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.patches import Rectangle
from matplotlib.transforms import Bbox
from matplotlib.patches import PathPatch
from matplotlib.path import Path
from matplotlib.transforms import Affine2D
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import BboxTransformFrom
from matplotlib.transforms import Affine2D
from matplotlib.transforms import Bbox
from matplotlib.transforms import BboxTransformTo
from matplotlib.transforms import Bbox